[package]
name = "eatmud"
version = "3.0.1"
edition = "2021"
default-run = "bench_kelly"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "*"
encoding_rs = "*"
ndarray = "*"

[lib]
crate_type = ["lib"]
